/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RegionRouteImport } from './routes/$region'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegionIndexRouteImport } from './routes/$region.index'
import { Route as TagSlugRouteImport } from './routes/tag.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminTaxonomyRouteImport } from './routes/admin.taxonomy'
import { Route as AdminGenerateRouteImport } from './routes/admin.generate'
import { Route as RegionTermsRouteImport } from './routes/$region.terms'
import { Route as RegionSearchRouteImport } from './routes/$region.search'
import { Route as RegionPrivacyRouteImport } from './routes/$region.privacy'
import { Route as RegionDisclaimerRouteImport } from './routes/$region.disclaimer'
import { Route as RegionContactRouteImport } from './routes/$region.contact'
import { Route as RegionBlogRouteImport } from './routes/$region.blog'
import { Route as RegionAboutRouteImport } from './routes/$region.about'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as RegionBlogIndexRouteImport } from './routes/$region.blog.index'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'
import { Route as RegionTagSlugRouteImport } from './routes/$region.tag.$slug'
import { Route as RegionCategorySlugRouteImport } from './routes/$region.category.$slug'
import { Route as RegionBlogSlugRouteImport } from './routes/$region.blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRoute = RegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegionIndexRoute = RegionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionRoute,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenerateRoute = AdminGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AdminRoute,
} as any)
const RegionTermsRoute = RegionTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => RegionRoute,
} as any)
const RegionSearchRoute = RegionSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => RegionRoute,
} as any)
const RegionPrivacyRoute = RegionPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => RegionRoute,
} as any)
const RegionDisclaimerRoute = RegionDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => RegionRoute,
} as any)
const RegionContactRoute = RegionContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => RegionRoute,
} as any)
const RegionBlogRoute = RegionBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => RegionRoute,
} as any)
const RegionAboutRoute = RegionAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => RegionRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const RegionBlogIndexRoute = RegionBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionBlogRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const RegionTagSlugRoute = RegionTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => RegionRoute,
} as any)
const RegionCategorySlugRoute = RegionCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => RegionRoute,
} as any)
const RegionBlogSlugRoute = RegionBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegionBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$region/about': typeof RegionAboutRoute
  '/$region/blog': typeof RegionBlogRouteWithChildren
  '/$region/contact': typeof RegionContactRoute
  '/$region/disclaimer': typeof RegionDisclaimerRoute
  '/$region/privacy': typeof RegionPrivacyRoute
  '/$region/search': typeof RegionSearchRoute
  '/$region/terms': typeof RegionTermsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/$region/': typeof RegionIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$region/blog/$slug': typeof RegionBlogSlugRoute
  '/$region/category/$slug': typeof RegionCategorySlugRoute
  '/$region/tag/$slug': typeof RegionTagSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/$region/blog/': typeof RegionBlogIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$region/about': typeof RegionAboutRoute
  '/$region/contact': typeof RegionContactRoute
  '/$region/disclaimer': typeof RegionDisclaimerRoute
  '/$region/privacy': typeof RegionPrivacyRoute
  '/$region/search': typeof RegionSearchRoute
  '/$region/terms': typeof RegionTermsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/$region': typeof RegionIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/$region/blog/$slug': typeof RegionBlogSlugRoute
  '/$region/category/$slug': typeof RegionCategorySlugRoute
  '/$region/tag/$slug': typeof RegionTagSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/$region/blog': typeof RegionBlogIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$region/about': typeof RegionAboutRoute
  '/$region/blog': typeof RegionBlogRouteWithChildren
  '/$region/contact': typeof RegionContactRoute
  '/$region/disclaimer': typeof RegionDisclaimerRoute
  '/$region/privacy': typeof RegionPrivacyRoute
  '/$region/search': typeof RegionSearchRoute
  '/$region/terms': typeof RegionTermsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/$region/': typeof RegionIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$region/blog/$slug': typeof RegionBlogSlugRoute
  '/$region/category/$slug': typeof RegionCategorySlugRoute
  '/$region/tag/$slug': typeof RegionTagSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/$region/blog/': typeof RegionBlogIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$region'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/disclaimer'
    | '/llms.txt'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/$region/about'
    | '/$region/blog'
    | '/$region/contact'
    | '/$region/disclaimer'
    | '/$region/privacy'
    | '/$region/search'
    | '/$region/terms'
    | '/admin/generate'
    | '/admin/taxonomy'
    | '/blog/$slug'
    | '/category/$slug'
    | '/tag/$slug'
    | '/$region/'
    | '/admin/'
    | '/blog/'
    | '/$region/blog/$slug'
    | '/$region/category/$slug'
    | '/$region/tag/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/$region/blog/'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/llms.txt'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/$region/about'
    | '/$region/contact'
    | '/$region/disclaimer'
    | '/$region/privacy'
    | '/$region/search'
    | '/$region/terms'
    | '/admin/generate'
    | '/admin/taxonomy'
    | '/blog/$slug'
    | '/category/$slug'
    | '/tag/$slug'
    | '/$region'
    | '/admin'
    | '/blog'
    | '/$region/blog/$slug'
    | '/$region/category/$slug'
    | '/$region/tag/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/$region/blog'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/$region'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/disclaimer'
    | '/llms.txt'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/$region/about'
    | '/$region/blog'
    | '/$region/contact'
    | '/$region/disclaimer'
    | '/$region/privacy'
    | '/$region/search'
    | '/$region/terms'
    | '/admin/generate'
    | '/admin/taxonomy'
    | '/blog/$slug'
    | '/category/$slug'
    | '/tag/$slug'
    | '/$region/'
    | '/admin/'
    | '/blog/'
    | '/$region/blog/$slug'
    | '/$region/category/$slug'
    | '/$region/tag/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/$region/blog/'
    | '/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegionRoute: typeof RegionRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  TagSlugRoute: typeof TagSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region': {
      id: '/$region'
      path: '/$region'
      fullPath: '/$region'
      preLoaderRoute: typeof RegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$region/': {
      id: '/$region/'
      path: '/'
      fullPath: '/$region/'
      preLoaderRoute: typeof RegionIndexRouteImport
      parentRoute: typeof RegionRoute
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generate': {
      id: '/admin/generate'
      path: '/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AdminGenerateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$region/terms': {
      id: '/$region/terms'
      path: '/terms'
      fullPath: '/$region/terms'
      preLoaderRoute: typeof RegionTermsRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/search': {
      id: '/$region/search'
      path: '/search'
      fullPath: '/$region/search'
      preLoaderRoute: typeof RegionSearchRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/privacy': {
      id: '/$region/privacy'
      path: '/privacy'
      fullPath: '/$region/privacy'
      preLoaderRoute: typeof RegionPrivacyRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/disclaimer': {
      id: '/$region/disclaimer'
      path: '/disclaimer'
      fullPath: '/$region/disclaimer'
      preLoaderRoute: typeof RegionDisclaimerRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/contact': {
      id: '/$region/contact'
      path: '/contact'
      fullPath: '/$region/contact'
      preLoaderRoute: typeof RegionContactRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/blog': {
      id: '/$region/blog'
      path: '/blog'
      fullPath: '/$region/blog'
      preLoaderRoute: typeof RegionBlogRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/about': {
      id: '/$region/about'
      path: '/about'
      fullPath: '/$region/about'
      preLoaderRoute: typeof RegionAboutRouteImport
      parentRoute: typeof RegionRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$region/blog/': {
      id: '/$region/blog/'
      path: '/'
      fullPath: '/$region/blog/'
      preLoaderRoute: typeof RegionBlogIndexRouteImport
      parentRoute: typeof RegionBlogRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$region/tag/$slug': {
      id: '/$region/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/$region/tag/$slug'
      preLoaderRoute: typeof RegionTagSlugRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/category/$slug': {
      id: '/$region/category/$slug'
      path: '/category/$slug'
      fullPath: '/$region/category/$slug'
      preLoaderRoute: typeof RegionCategorySlugRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/blog/$slug': {
      id: '/$region/blog/$slug'
      path: '/$slug'
      fullPath: '/$region/blog/$slug'
      preLoaderRoute: typeof RegionBlogSlugRouteImport
      parentRoute: typeof RegionBlogRoute
    }
  }
}

interface RegionBlogRouteChildren {
  RegionBlogSlugRoute: typeof RegionBlogSlugRoute
  RegionBlogIndexRoute: typeof RegionBlogIndexRoute
}

const RegionBlogRouteChildren: RegionBlogRouteChildren = {
  RegionBlogSlugRoute: RegionBlogSlugRoute,
  RegionBlogIndexRoute: RegionBlogIndexRoute,
}

const RegionBlogRouteWithChildren = RegionBlogRoute._addFileChildren(
  RegionBlogRouteChildren,
)

interface RegionRouteChildren {
  RegionAboutRoute: typeof RegionAboutRoute
  RegionBlogRoute: typeof RegionBlogRouteWithChildren
  RegionContactRoute: typeof RegionContactRoute
  RegionDisclaimerRoute: typeof RegionDisclaimerRoute
  RegionPrivacyRoute: typeof RegionPrivacyRoute
  RegionSearchRoute: typeof RegionSearchRoute
  RegionTermsRoute: typeof RegionTermsRoute
  RegionIndexRoute: typeof RegionIndexRoute
  RegionCategorySlugRoute: typeof RegionCategorySlugRoute
  RegionTagSlugRoute: typeof RegionTagSlugRoute
}

const RegionRouteChildren: RegionRouteChildren = {
  RegionAboutRoute: RegionAboutRoute,
  RegionBlogRoute: RegionBlogRouteWithChildren,
  RegionContactRoute: RegionContactRoute,
  RegionDisclaimerRoute: RegionDisclaimerRoute,
  RegionPrivacyRoute: RegionPrivacyRoute,
  RegionSearchRoute: RegionSearchRoute,
  RegionTermsRoute: RegionTermsRoute,
  RegionIndexRoute: RegionIndexRoute,
  RegionCategorySlugRoute: RegionCategorySlugRoute,
  RegionTagSlugRoute: RegionTagSlugRoute,
}

const RegionRouteWithChildren =
  RegionRoute._addFileChildren(RegionRouteChildren)

interface AdminRouteChildren {
  AdminGenerateRoute: typeof AdminGenerateRoute
  AdminTaxonomyRoute: typeof AdminTaxonomyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGenerateRoute: AdminGenerateRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegionRoute: RegionRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  TagSlugRoute: TagSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
